export const CART_TYPES = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  ADD_ITEM_QUANTITY: 'ADD_ITEM_QUANTITY',
  REMOVE_ITEM_QUANTITY: 'REMOVE_ITEM_QUANTITY'
}